__author__ = 'azh'


class ResponseStatusCodes:
    POST_SUCCESS = 201
    PUT_SUCCESS = 200
    DELETE_SUCCESS = 200
    GET_SUCCESS = 200
    BAD_REQUEST_ERROR = 400
    NOT_AUTHENTICATED_ERROR = 405
    NOT_AUTHORIZED_ERROR = 401
    UNHANDLED_SERVER_ERROR = 500
    PAGE_NOT_FOUND_ERROR = 404
