from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from pyutil.pdf.farsi_text import FarsiText

__author__ = 'root'


class FooterCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self.pages = []

    def showPage(self):
        self.pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        page_count = len(self.pages)
        for page in self.pages:
            self.__dict__.update(page)
            self.draw_canvas(page_count)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_canvas(self, page_count):

        page = FarsiText.get_farsi_text("صفحه {} از {}".format(FarsiText.get_farsi_numbers(str(self._pageNumber)),
                                                               FarsiText.get_farsi_numbers(str(page_count))))
        copyright_text = 'generated by {}'.format('Motanaweb Co.')
        x = 128
        self.saveState()
        self.setStrokeColor(colors.lavender)
        self.setLineWidth(0.3)
        self.line(66, 78, A4[0] - 66, 78)
        self.setStrokeColorRGB(0, 0, 0)
        self.setFont('Persian', 8)
        self.drawString(A4[0]/2 - len(page)/2, 65, page)
        self.drawString(A4[0]/2 - len(copyright_text), 55, copyright_text)
        self.restoreState()


